INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Notebook Dell Inspiron 15', 3899.00, 10, 4.2, 'NOTEBOOK');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Smartphone Samsung Galaxy S23', 4599.00, 15, 4.8, 'SMARTPHONE');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('iPhone 14 Pro Max', 7899.00, 8, 4.9, 'SMARTPHONE');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Smart TV LG 55" 4K', 2799.00, 12, 3.9, 'TV');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Console PlayStation 5', 3899.00, 6, 4.7, 'VIDEOGAME');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Console Xbox Series X', 3799.00, 7, 4.5, 'VIDEOGAME');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Cadeira Gamer ThunderX3', 1299.00, 20, 3.2, 'PERIFERICO');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Mouse Logitech MX Master 3', 499.00, 30, 4.9, 'PERIFERICO');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Teclado Mecânico Redragon Kumara', 299.00, 25, 3.8, 'PERIFERICO');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Monitor Gamer AOC 27" 144Hz', 1499.00, 14, 4.3, 'MONITOR');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('HD Externo Seagate 2TB', 549.00, 18, 3.5, 'ARMAZENAMENTO');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('SSD Kingston NV2 1TB NVMe', 379.00, 22, 4.6, 'ARMAZENAMENTO');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Placa de Vídeo RTX 4070 Ti', 4999.00, 5, 4.8, 'COMPONENTE_PC');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Processador AMD Ryzen 7 5800X', 1899.00, 9, 4.4, 'COMPONENTE_PC');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Placa-mãe ASUS TUF B550M', 1099.00, 11, 3.6, 'COMPONENTE_PC');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Memória RAM Corsair 16GB DDR4', 299.00, 40, 4.1, 'COMPONENTE_PC');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Fonte Corsair 650W 80 Plus Bronze', 499.00, 13, 2.9, 'COMPONENTE_PC');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Gabinete Gamer NZXT H510', 599.00, 10, 4.0, 'COMPONENTE_PC');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Headset HyperX Cloud II', 599.00, 21, 4.5, 'PERIFERICO');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Impressora HP DeskJet Ink Advantage', 449.00, 16, 2.8, 'IMPRESSORA');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Kindle Paperwhite 11ª Geração', 699.00, 9, 4.7, 'SMARTPHONE');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Câmera GoPro Hero 11', 2599.00, 7, 4.2, 'FOTO_VIDEO');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Apple Watch Series 9', 4299.00, 8, 4.6, 'WEARABLE');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Xiaomi Mi Band 8', 299.00, 25, 3.9, 'WEARABLE');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Ar Condicionado LG Dual Inverter 12000 BTUs', 2299.00, 6, 4.3, 'ELETRODOMESTICO');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Geladeira Brastemp Frost Free 375L', 2999.00, 4, 3.7, 'ELETRODOMESTICO');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Máquina de Lavar Electrolux 11Kg', 2399.00, 5, 4.1, 'ELETRODOMESTICO');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Micro-ondas Panasonic 32L', 749.00, 12, 3.4, 'ELETRODOMESTICO');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Fogão 5 Bocas Consul Inox', 1899.00, 3, 2.7, 'ELETRODOMESTICO');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Cafeteira Nespresso Essenza Mini', 599.00, 18, 4.6, 'ELETRODOMESTICO');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Aspirador de Pó Robô Roomba i3', 2899.00, 4, 4.2, 'ELETRODOMESTICO');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Smart Speaker Amazon Echo Dot 5ª Geração', 379.00, 28, 4.8, 'CASA_INTELIGENTE');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Caixa de Som JBL Charge 5', 899.00, 17, 4.4, 'AUDIO');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Violão Yamaha C40', 899.00, 8, 3.6, 'INSTRUMENTO_MUSICAL');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Teclado Musical Casio CT-X700', 1399.00, 5, 3.9, 'INSTRUMENTO_MUSICAL');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Bicicleta Caloi Elite Carbon', 7999.00, 2, 4.5, 'ESPORTE');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Patinete Elétrico Xiaomi Mi Scooter 3', 2999.00, 6, 4.0, 'MOBILIDADE');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Drone DJI Mini 3 Pro', 4699.00, 3, 4.7, 'FOTO_VIDEO');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Relógio Casio G-Shock', 699.00, 14, 4.3, 'WEARABLE');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Perfume Paco Rabanne 1 Million 100ml', 499.00, 20, 3.8, 'PERFUME');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Tênis Nike Air Max 270', 899.00, 19, 4.2, 'MODA');
INSERT INTO tb_product (name, price, stock, assessment, category) VALUES ('Notebook Apple MacBook Air M2', 10499.00, 5, 4.9, 'NOTEBOOK');