INSERT INTO tb_product (name, price, quantity) VALUES ('Notebook Dell Inspiron 15', 3899.00, 10);
INSERT INTO tb_product (name, price, quantity) VALUES ('Smartphone Samsung Galaxy S23', 4599.00, 15);
INSERT INTO tb_product (name, price, quantity) VALUES ('iPhone 14 Pro Max', 7899.00, 8);
INSERT INTO tb_product (name, price, quantity) VALUES ('Smart TV LG 55" 4K', 2799.00, 12);
INSERT INTO tb_product (name, price, quantity) VALUES ('Console PlayStation 5', 3899.00, 6);
INSERT INTO tb_product (name, price, quantity) VALUES ('Console Xbox Series X', 3799.00, 7);
INSERT INTO tb_product (name, price, quantity) VALUES ('Cadeira Gamer ThunderX3', 1299.00, 20);
INSERT INTO tb_product (name, price, quantity) VALUES ('Mouse Logitech MX Master 3', 499.00, 30);
INSERT INTO tb_product (name, price, quantity) VALUES ('Teclado Mecânico Redragon Kumara', 299.00, 25);
INSERT INTO tb_product (name, price, quantity) VALUES ('Monitor Gamer AOC 27" 144Hz', 1499.00, 14);
INSERT INTO tb_product (name, price, quantity) VALUES ('HD Externo Seagate 2TB', 549.00, 18);
INSERT INTO tb_product (name, price, quantity) VALUES ('SSD Kingston NV2 1TB NVMe', 379.00, 22);
INSERT INTO tb_product (name, price, quantity) VALUES ('Placa de Vídeo RTX 4070 Ti', 4999.00, 5);
INSERT INTO tb_product (name, price, quantity) VALUES ('Processador AMD Ryzen 7 5800X', 1899.00, 9);
INSERT INTO tb_product (name, price, quantity) VALUES ('Placa-mãe ASUS TUF B550M', 1099.00, 11);
INSERT INTO tb_product (name, price, quantity) VALUES ('Memória RAM Corsair 16GB DDR4', 299.00, 40);
INSERT INTO tb_product (name, price, quantity) VALUES ('Fonte Corsair 650W 80 Plus Bronze', 499.00, 13);
INSERT INTO tb_product (name, price, quantity) VALUES ('Gabinete Gamer NZXT H510', 599.00, 10);
INSERT INTO tb_product (name, price, quantity) VALUES ('Headset HyperX Cloud II', 599.00, 21);
INSERT INTO tb_product (name, price, quantity) VALUES ('Impressora HP DeskJet Ink Advantage', 449.00, 16);
INSERT INTO tb_product (name, price, quantity) VALUES ('Kindle Paperwhite 11ª Geração', 699.00, 9);
INSERT INTO tb_product (name, price, quantity) VALUES ('Câmera GoPro Hero 11', 2599.00, 7);
INSERT INTO tb_product (name, price, quantity) VALUES ('Apple Watch Series 9', 4299.00, 8);
INSERT INTO tb_product (name, price, quantity) VALUES ('Xiaomi Mi Band 8', 299.00, 25);
INSERT INTO tb_product (name, price, quantity) VALUES ('Ar Condicionado LG Dual Inverter 12000 BTUs', 2299.00, 6);
INSERT INTO tb_product (name, price, quantity) VALUES ('Geladeira Brastemp Frost Free 375L', 2999.00, 4);
INSERT INTO tb_product (name, price, quantity) VALUES ('Máquina de Lavar Electrolux 11Kg', 2399.00, 5);
INSERT INTO tb_product (name, price, quantity) VALUES ('Micro-ondas Panasonic 32L', 749.00, 12);
INSERT INTO tb_product (name, price, quantity) VALUES ('Fogão 5 Bocas Consul Inox', 1899.00, 3);
INSERT INTO tb_product (name, price, quantity) VALUES ('Cafeteira Nespresso Essenza Mini', 599.00, 18);
INSERT INTO tb_product (name, price, quantity) VALUES ('Aspirador de Pó Robô Roomba i3', 2899.00, 4);
INSERT INTO tb_product (name, price, quantity) VALUES ('Smart Speaker Amazon Echo Dot 5ª Geração', 379.00, 28);
INSERT INTO tb_product (name, price, quantity) VALUES ('Caixa de Som JBL Charge 5', 899.00, 17);
INSERT INTO tb_product (name, price, quantity) VALUES ('Violão Yamaha C40', 899.00, 8);
INSERT INTO tb_product (name, price, quantity) VALUES ('Teclado Musical Casio CT-X700', 1399.00, 5);
INSERT INTO tb_product (name, price, quantity) VALUES ('Bicicleta Caloi Elite Carbon', 7999.00, 2);
INSERT INTO tb_product (name, price, quantity) VALUES ('Patinete Elétrico Xiaomi Mi Scooter 3', 2999.00, 6);
INSERT INTO tb_product (name, price, quantity) VALUES ('Drone DJI Mini 3 Pro', 4699.00, 3);
INSERT INTO tb_product (name, price, quantity) VALUES ('Relógio Casio G-Shock', 699.00, 14);
INSERT INTO tb_product (name, price, quantity) VALUES ('Perfume Paco Rabanne 1 Million 100ml', 499.00, 20);
INSERT INTO tb_product (name, price, quantity) VALUES ('Tênis Nike Air Max 270', 899.00, 19);
INSERT INTO tb_product (name, price, quantity) VALUES ('Notebook Apple MacBook Air M2', 10499.00, 5);